export const HOOKS_DIR = ".recall/hooks";
export const PRE_COMMIT_HOOK_PATH = ".recall/hooks/pre-commit";
export const HOOKS_PATH_ACTIVATION_COMMAND = "git config core.hooksPath .recall/hooks";

export const SESSION_START_HOOK_PATH = ".claude/hooks/session-start.sh";
export const CLAUDE_SETTINGS_PATH = ".claude/settings.json";

/**
 * Render a deterministic POSIX `sh` Claude Code SessionStart hook.
 *
 * Claude Code runs this before the first prompt of every session and injects its stdout
 * `additionalContext` into the model. It lists the repository's accepted ADRs and modules so a fresh
 * agent reliably knows the durable memory exists and where to read it. It is strictly read-only:
 * it only lists files and never modifies anything, makes no network calls, and runs no AI.
 */
export function renderSessionStartHook(): string {
  return `#!/bin/sh
# Recall OS Claude Code SessionStart hook.
# Generated by \`recall init\`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

adrs=$(ls docs/adrs/ADR-*.md 2>/dev/null | sed 's|.*/||;s|\\.md$||' | tr '\\n' ' ')
modules=$(ls -d docs/30-modules/*/ 2>/dev/null | sed 's|docs/30-modules/||;s|/$||' | tr '\\n' ' ')

context="Recall OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (docs/adrs/): \${adrs:-none yet}. Modules (docs/30-modules/): \${modules:-none yet}. Run 'recall doctor' before claiming work complete."

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\\n' "$context"
`;
}

/**
 * Claude Code settings that wire the SessionStart hook. Generated only when no settings file exists,
 * since the safe write policy never overwrites a user's existing settings.
 */
export function renderClaudeSettings(): string {
  return `${JSON.stringify(
    {
      hooks: {
        SessionStart: [
          {
            matcher: "startup",
            hooks: [{ type: "command", command: `./${SESSION_START_HOOK_PATH}` }],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

/**
 * Render a deterministic POSIX `sh` pre-commit hook.
 *
 * The hook runs `recall doctor` first, then each configured gate in order. Gates come from
 * `.recall/config.json` (`preCommitGates`), so the toolchain choice stays in user config rather than
 * in core. The hook does not modify git configuration; activation is a deliberate human step.
 */
export function renderPreCommitHook(gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Recall OS pre-commit hook.",
    "# Generated by `recall init`. Edit gates in .recall/config.json (preCommitGates),",
    "# then re-run `recall init --force` to regenerate this hook.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "recall doctor",
  ];

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}
