export const HOOKS_DIR = ".persist/hooks";
export const PRE_COMMIT_HOOK_PATH = ".persist/hooks/pre-commit";
export const PRE_PUSH_HOOK_PATH = ".persist/hooks/pre-push";
export const HOOKS_PATH_ACTIVATION_COMMAND = "git config core.hooksPath .persist/hooks";

export const SESSION_START_HOOK_PATH = ".claude/hooks/session-start.sh";
export const CLAUDE_SETTINGS_PATH = ".claude/settings.json";

/**
 * Render a deterministic POSIX `sh` Claude Code SessionStart hook.
 *
 * Claude Code runs this before the first prompt of every session and injects its stdout
 * `additionalContext` into the model. It lists the repository's accepted ADRs and modules so a fresh
 * agent reliably knows the durable memory exists and where to read it. It is strictly read-only:
 * it only lists files and never modifies anything, makes no network calls, and runs no AI.
 */
export function renderSessionStartHook(): string {
  return `#!/bin/sh
# Persist OS Claude Code SessionStart hook.
# Generated by \`persist init\`. Injects a repository-memory map into every Claude Code session so a
# fresh agent reliably loads durable memory. Wired in .claude/settings.json. Read-only.

adrs=$(ls docs/adrs/ADR-*.md 2>/dev/null | sed 's|.*/||;s|\\.md$||' | tr '\\n' ' ')
modules=$(ls -d docs/30-modules/*/ 2>/dev/null | sed 's|docs/30-modules/||;s|/$||' | tr '\\n' ' ')

context="Persist OS repository memory is the source of truth over chat history. Before non-trivial work, read AGENTS.md and the docs it routes to; repository rules override model preference. Accepted ADRs (docs/adrs/): \${adrs:-none yet}. Modules (docs/30-modules/): \${modules:-none yet}. Use the Persist OS CLI commands listed in AGENTS.md (persist feature/adr/module create, persist adr accept and supersede, persist doctor) yourself; do not web-search them. Run 'persist doctor' before claiming work complete."

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\\n' "$context"
`;
}

/**
 * Claude Code settings that wire the SessionStart hook. Generated only when no settings file exists,
 * since the safe write policy never overwrites a user's existing settings.
 */
export function renderClaudeSettings(): string {
  return `${JSON.stringify(
    {
      hooks: {
        SessionStart: [
          {
            matcher: "startup",
            hooks: [{ type: "command", command: `./${SESSION_START_HOOK_PATH}` }],
          },
        ],
      },
    },
    null,
    2,
  )}\n`;
}

/**
 * Render a deterministic POSIX `sh` pre-commit hook.
 *
 * The hook runs `persist doctor` first, then each configured gate in order. Gates come from
 * `.persist/config.json` (`preCommitGates`), so the toolchain choice stays in user config rather than
 * in core. The hook does not modify git configuration; activation is a deliberate human step.
 */
export function renderPreCommitHook(gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Persist OS pre-commit hook.",
    "# Generated by `persist init`. Edit gates in .persist/config.json (preCommitGates),",
    "# then re-run `persist init --force` to regenerate this hook.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "persist doctor",
  ];

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}

/**
 * Render a deterministic POSIX `sh` pre-push hook — the final regression gate before code leaves the
 * machine. It runs `persist doctor` and the same configured gates as pre-commit against everything
 * being pushed, catching commits made with `--no-verify`, on another machine, or before the
 * pre-commit hook was activated. It does not modify git configuration; activation is the same
 * deliberate `core.hooksPath` step.
 */
export function renderPrePushHook(gates: string[]): string {
  const lines = [
    "#!/bin/sh",
    "# Persist OS pre-push hook.",
    "# Generated by `persist init`. The final regression gate before code leaves your machine: it runs",
    "# `persist doctor` and your configured gates against everything being pushed (catching commits",
    "# made with --no-verify or before the pre-commit hook was active).",
    "# Edit gates in .persist/config.json (preCommitGates), then re-run `persist init --force`.",
    "# Enable once per clone with:",
    `#   ${HOOKS_PATH_ACTIVATION_COMMAND}`,
    "set -e",
    "",
    "persist doctor",
  ];

  for (const gate of gates) {
    lines.push(gate);
  }

  lines.push("");

  return lines.join("\n");
}
